server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8070/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    com.netflix: WARN
    org.springframework.web: WARN
    com.bazinga.eg: DEBUG