spring:
  datasource:
    url: jdbc:mysql://localhost/user
    username: root
    password: Asd123!@#
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  sql:
    init:
      platform: mysql