server:
  port: 8081

spring:
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1
    username: sa
    password: secret
  jpa:
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
  h2:
    console:
      enabled: true
  sql:
    init:
      platform: h2
  cloud:
    service-registry:
      auto-registration:
        enabled: false

eureka:
  client:
    enabled: false
    register-with-eureka: false
    fetch-registry: false

logging:
  level:
    com.netflix: WARN
    org.springframework.web: WARN
    com.bazinga.eg: DEBUG